/*const coursesData = [
    { name: "Programming 101", description: "Intro to programming", price: 99, themes: ["Programming"], level: "level-basic", popularity: 120 },
    { name: "Advanced Design", description: "Learn advanced design techniques", price: 199, themes: ["Design"], level: "level-intermediate", popularity: 85 },
    { name: "Marketing Mastery", description: "Master marketing skills", price: 149, themes: ["Marketing"], level: "level-advanced", popularity: 95 },
    { name: "Data Science", description: "Learn the basics of data science", price: 129, themes: ["Programming"], level: "level-basic", popularity: 100 },
    { name: "UX/UI Design", description: "Learn UX/UI design principles", price: 179, themes: ["Design"], level: "level-intermediate", popularity: 150 },
    { name: "Business Analytics", description: "Understand business analytics", price: 149, themes: ["Business"], level: "level-intermediate", popularity: 110 },
    { name: "Web Development", description: "Become a web developer", price: 199, themes: ["Programming"], level: "level-basic", popularity: 220 },
    { name: "Python Programming", description: "Learn Python programming language", price: 0, themes: ["Programming"], level: "level-basic", popularity: 300 },
    { name: "Digital Marketing", description: "Master digital marketing", price: 0, themes: ["Marketing"], level: "level-basic", popularity: 160 },
    { name: "JavaScript Fundamentals", description: "Master JavaScript basics", price: 149, themes: ["Programming"], level: "level-basic", popularity: 280 },
    { name: "React Development", description: "Build modern web apps with React", price: 199, themes: ["Programming"], level: "level-intermediate", popularity: 260 },
    { name: "Node.js Backend", description: "Server-side development with Node.js", price: 179, themes: ["Programming"], level: "level-intermediate", popularity: 230 },
    { name: "Mobile App Design", description: "Design principles for mobile applications", price: 189, themes: ["Design"], level: "level-intermediate", popularity: 170 },
    { name: "Graphic Design Basics", description: "Foundation of graphic design", price: 129, themes: ["Design"], level: "level-basic", popularity: 190 },
    { name: "Advanced Marketing Analytics", description: "Deep dive into marketing metrics", price: 229, themes: ["Marketing"], level: "level-advanced", popularity: 140 },
    { name: "Content Marketing", description: "Create engaging content strategy", price: 159, themes: ["Marketing"], level: "level-intermediate", popularity: 175 },
    { name: "Financial Management", description: "Understand finance basics", price: 199, themes: ["Finance"], level: "level-basic", popularity: 145 },
    { name: "Investment Strategies", description: "Learn smart investment techniques", price: 249, themes: ["Finance"], level: "level-intermediate", popularity: 130 },
    { name: "Public Speaking", description: "Master public speaking skills", price: 129, themes: ["Personal Development"], level: "level-basic", popularity: 200 },
    { name: "Leadership Skills", description: "Develop effective leadership", price: 179, themes: ["Personal Development"], level: "level-intermediate", popularity: 185 },
    { name: "English for Business", description: "Business English communication", price: 149, themes: ["Languages"], level: "level-intermediate", popularity: 210 },
    { name: "Spanish Basics", description: "Learn Spanish fundamentals", price: 99, themes: ["Languages"], level: "level-basic", popularity: 165 },
    { name: "Digital Photography", description: "Master digital photography", price: 169, themes: ["Art"], level: "level-basic", popularity: 155 },
    { name: "Oil Painting", description: "Learn oil painting techniques", price: 189, themes: ["Art"], level: "level-intermediate", popularity: 125 },
    { name: "Angular Development", description: "Build apps with Angular", price: 189, themes: ["Programming"], level: "level-intermediate", popularity: 240 },
    { name: "Vue.js Essentials", description: "Frontend development with Vue", price: 169, themes: ["Programming"], level: "level-intermediate", popularity: 220 },
    { name: "PHP Development", description: "Server-side programming with PHP", price: 159, themes: ["Programming"], level: "level-basic", popularity: 195 },
    { name: "Ruby on Rails", description: "Web development with Rails", price: 189, themes: ["Programming"], level: "level-intermediate", popularity: 180 },
    { name: "Swift iOS Development", description: "Build iOS applications", price: 199, themes: ["Programming"], level: "level-intermediate", popularity: 210 },
    { name: "Android Development", description: "Create Android applications", price: 189, themes: ["Programming"], level: "level-intermediate", popularity: 205 },
    { name: "3D Modeling", description: "Learn 3D modeling basics", price: 199, themes: ["Design"], level: "level-basic", popularity: 160 },
    { name: "Motion Graphics", description: "Create engaging animations", price: 189, themes: ["Design"], level: "level-intermediate", popularity: 175 },
    { name: "Brand Design", description: "Create memorable brand identities", price: 169, themes: ["Design"], level: "level-intermediate", popularity: 185 },
    { name: "UI Animation", description: "Animate user interfaces", price: 159, themes: ["Design"], level: "level-intermediate", popularity: 170 },
    { name: "Social Media Marketing", description: "Master social media strategy", price: 149, themes: ["Marketing"], level: "level-basic", popularity: 250 },
    { name: "Email Marketing", description: "Create effective email campaigns", price: 129, themes: ["Marketing"], level: "level-intermediate", popularity: 190 },
    { name: "SEO Fundamentals", description: "Learn search engine optimization", price: 159, themes: ["Marketing"], level: "level-basic", popularity: 230 },
    { name: "Google Ads", description: "Master Google advertising", price: 179, themes: ["Marketing"], level: "level-intermediate", popularity: 210 },
    { name: "Business Strategy", description: "Develop business strategies", price: 199, themes: ["Business"], level: "level-intermediate", popularity: 180 },
    { name: "Project Management", description: "Learn project management skills", price: 189, themes: ["Business"], level: "level-intermediate", popularity: 195 },
    { name: "Machine Learning Advanced", description: "Advanced ML concepts", price: 299, themes: ["Programming"], level: "level-advanced", popularity: 270 },
    { name: "Blockchain Development", description: "Build blockchain applications", price: 249, themes: ["Programming"], level: "level-advanced", popularity: 240 },
    { name: "Cloud Computing", description: "Master cloud technologies", price: 219, themes: ["Programming"], level: "level-intermediate", popularity: 225 },
    { name: "DevOps Practices", description: "Learn DevOps methodology", price: 229, themes: ["Programming"], level: "level-advanced", popularity: 215 },
    { name: "Cybersecurity Basics", description: "Introduction to cybersecurity", price: 199, themes: ["Programming"], level: "level-basic", popularity: 235 }
];

module.exports = coursesData;*/